version: '3.4'

services:
  blazor-server-status:
    image: ${DOCKER_REGISTRY-}blazorserverstatus
    build:
      context: .
      dockerfile: blazor-server-status/Dockerfile
  redis_service:
    image: redis:6.2-alpine
    ports:
    - "6379:6379"
  redis_teste:
    image: redis:6.2-alpine
    ports:
    - "6366:6379"